language: node_js
node_js: stable
dist: trusty

cache: yarn

before_install:
  - npm install -g codecov

install:
  - yarn

script:
  - npm t
  - codecov

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: main
    script:
      - npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release
